sudo: false
dist: trusty
language: go
go:
- 1.11.x
go_import_path: github.com/elsevier-core-engineering/replicator
before_script:
- wget https://releases.hashicorp.com/consul/1.4.2/consul_1.4.2_linux_amd64.zip
- unzip -d $GOPATH/bin consul_1.4.2_linux_amd64.zip
install:
- go get github.com/golang/lint/golint
- go get github.com/mitchellh/gox
script:
- make test
after_success:
- if [[ -n "$TRAVIS_TAG" ]]; then make release; fi
notifications:
  email: true
deploy:
  provider: releases
  go: 1.11.x
  file:
    - pkg/darwin-386-replicator
    - pkg/darwin-amd64-replicator
    - pkg/freebsd-386-replicator
    - pkg/freebsd-amd64-replicator
    - pkg/freebsd-arm-replicator
    - pkg/linux-386-replicator
    - pkg/linux-amd64-replicator
    - pkg/linux-arm-replicator
  skip_cleanup: true
  on:
    tags: true
